image_width: 640
image_height: 480
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [242.41316,   0.01212, 318.50326,
           0.     , 241.51807, 241.35501,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.033452, 0.859663, -1.388398, 0.457118]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [242.41316,   0.01212, 318.50326,   0.     ,
           0.     , 241.51807, 241.35501,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
